export const projects = [
  {
    name: "Website Revamp",
    isActive: true,
    teams: [
      {
        name: "Design Team",
        members: [
          { name: "Sophia Walker", image: "sophia.jpg" },
          { name: "Liam Moore", image: "liam.jpg" },
        ],
        tasks: [
          {
            name: "Finalize UI Components",
            assignedTo: ["Sophia Walker"],
            status: "In Progress",
            priority: "High",
            due: "2025-03-05",
            keyPoints: [
              "Ensure consistency in colors, typography, and spacing.",
              "Create reusable components for buttons, inputs, and modals.",
              "Align with brand guidelines and accessibility standards.",
              "Test responsiveness across different breakpoints.",
              "Prepare design files for frontend handoff.",
            ],
            lastUpdate: "Finalizing UI Components",
            lastUpdateBy: "Liam Moore",
            lastUpdateOn: "10:30AM, 20/01/2025",
          },
          {
            name: "Design Mobile Layouts",
            assignedTo: ["Liam Moore"],
            status: "In Progress",
            priority: "Medium",
            due: "2025-03-10",
            keyPoints: [
              "Refine mobile layouts for better user experience.",
              "Ensure a seamless transition from desktop to mobile.",
              "Optimize touch interactions and navigation.",
              "Implement scalable typography and grid systems.",
              "Validate designs through usability testing.",
            ],
            lastUpdate: "Working on layout refinements",
            lastUpdateBy: "Liam Moore",
            lastUpdateOn: "11:45AM, 19/01/2025",
          },
        ],
      },
      {
        name: "Frontend Team",
        members: [
          { name: "Emma Scott", image: "emma.jpg" },
          { name: "James Carter", image: "james.jpg" },
          { name: "Noah Brown", image: "noah.jpg" },
        ],
        tasks: [
          {
            name: "Implement UI Components",
            assignedTo: ["Emma Scott"],
            status: "In Progress",
            priority: "High",
            due: "2025-03-15",
            keyPoints: [
              "Convert design components into reusable React components.",
              "Ensure responsiveness and accessibility compliance.",
              "Maintain consistency with design team guidelines.",
              "Optimize performance using best practices.",
            ],
            lastUpdate: "Developing Core Pages",
            lastUpdateBy: "James Carter",
            lastUpdateOn: "09:00AM, 18/01/2025",
          },
          {
            name: "Develop Core Pages",
            assignedTo: ["James Carter", "Noah Brown"],
            status: "Not Started",
            priority: "Medium",
            due: "2025-03-20",
            keyPoints: [
              "Implement homepage, about, and services pages.",
              "Ensure routing is set up correctly.",
              "Use reusable components for headers, footers, and sections.",
              "Test for responsiveness and accessibility compliance.",
            ],
            lastUpdate: "Planning structure",
            lastUpdateBy: "James Carter",
            lastUpdateOn: "08:30AM, 17/01/2025",
          },
          {
            name: "Integrate APIs",
            assignedTo: ["James Carter", "Noah Brown"],
            status: "Not Started",
            priority: "High",
            due: "2025-03-25",
            keyPoints: [
              "Connect frontend to backend endpoints.",
              "Handle authentication and authorization.",
              "Implement error handling and loading states.",
              "Optimize API calls for performance.",
            ],
            lastUpdate: "API schema discussion",
            lastUpdateBy: "Noah Brown",
            lastUpdateOn: "02:00PM, 16/01/2025",
          },
          {
            name: "Write Unit Tests",
            assignedTo: ["James Carter", "Noah Brown"],
            status: "Not Started",
            priority: "Medium",
            due: "2025-03-30",
            keyPoints: [
              "Write tests for key components and functions.",
              "Ensure test coverage for UI interactions.",
              "Use Jest and React Testing Library.",
              "Mock API responses where necessary.",
            ],
            lastUpdate: "Testing strategy outlined",
            lastUpdateBy: "James Carter",
            lastUpdateOn: "03:30PM, 15/01/2025",
          },
        ],
      },
      {
        name: "Backend Team",
        lastUpdate: "Refactoring API Endpoints",
        lastUpdateBy: "Emma Scott",
        members: [
          { name: "Emma Scott", image: "emma.jpg" },
          { name: "James Carter", image: "james.jpg" },
          { name: "Noah Brown", image: "noah.jpg" },
        ],
        tasks: [
          {
            name: "Refactor API Endpoints",
            assignedTo: ["Emma Scott"],
            status: "In Progress",
            priority: "High",
            due: "2025-03-12",
            keyPoints: [
              "Optimize endpoint performance and security.",
              "Ensure proper input validation and error handling.",
              "Update API documentation.",
              "Improve database query efficiency.",
            ],
            lastUpdate: "Improving security measures",
            lastUpdateBy: "Emma Scott",
            lastUpdateOn: "12:00PM, 14/01/2025",
          },
          {
            name: "Optimize Database Queries",
            assignedTo: ["James Carter", "Noah Brown"],
            status: "Not Started",
            priority: "High",
            due: "2025-03-18",
            keyPoints: [
              "Analyze slow queries and optimize indexing.",
              "Implement caching where applicable.",
              "Ensure data consistency and reliability.",
              "Perform load testing on database operations.",
            ],
            lastUpdate: "Identifying slow queries",
            lastUpdateBy: "Noah Brown",
            lastUpdateOn: "10:00AM, 13/01/2025",
          },
        ],
      },
      {
        name: "QA Team",
        lastUpdate: "Conducting Functional Testing",
        lastUpdateBy: "Olivia Adams",
        members: [
          { name: "Olivia Adams", image: "olivia.jpg" },
          { name: "William Garcia", image: "william.jpg" },
        ],
        tasks: [
          {
            name: "Conduct Functional Testing",
            assignedTo: ["Olivia Adams"],
            status: "In Progress",
            priority: "High",
            due: "2025-03-22",
            keyPoints: [
              "Test all core functionalities of the application.",
              "Report and document any issues found.",
              "Ensure edge cases are covered.",
              "Work closely with the development team on bug fixes.",
            ],
            lastUpdate: "Identifying critical bugs",
            lastUpdateBy: "Olivia Adams",
            lastUpdateOn: "04:00PM, 12/01/2025",
          },
        ],
      },
    ],
  },
];
