import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/providers/redux-provider";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import Sidebar from "@/components/sidebar";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} relative w-full h-screen overflow-hidden flex`}
      >
        <NuqsAdapter>
          <ReduxProvider>
            <Sidebar />
            {children}
          </ReduxProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
